const numbers = [1,2,3,4,5,6,7]
// here the const square stores the new array generated by map method in which a function is called that is itself declared inisde the .map() method where element is used as parameter
const squares = numbers.map((Element) => Math.pow(Element, 2))
const cubes = numbers.map((Element) => Math.pow(Element, 3))
const odd = numbers.filter((Element) => Element % 2 !== 0)
const total = numbers.reduce((accumulator, Element) => accumulator + Element)


console.log(squares);
console.log(cubes);
console.log(odd);
console.log(total);